spring:
  application:
    name: order-service

server:
  port: 8081

service:
  payment-url: ${PAYMENT_BASE_URL:http://localhost:8082}
  inventory-url: ${INVENTORY_BASE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [trace_id=%X{trace_id:-} span_id=%X{span_id:-}] [%thread] %logger{36} - %msg%n"
